---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "isreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "isreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-build-" .Values.name  | quote }}
  namespace: {{ required "Missing required value project" .Values.buildNamespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "istreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "istreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-build-" .Values.name  | quote }}
  namespace: {{ required "Missing required value project" .Values.buildNamespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "istwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "istwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-build-" .Values.name  | quote }}
  namespace: {{ required "Missing required value project" .Values.buildNamespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "bcget"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "bcget"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-build-" .Values.name  | quote }}
  namespace: {{ required "Missing required value project" .Values.buildNamespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "bcpatch"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "bcpatch"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-build-" .Values.name  | quote }}
  namespace: {{ required "Missing required value project" .Values.buildNamespace | quote }}
