# Name: The name assigned to all of the frontend objects defined in this template.
name: ocd-builder-webhook
# Memory Limit: Maximum amount of memory the container can use.
memory_limit: 512Mi
# Application Hostname: The exposed hostname that will route to the Node.js service, if left blank a value will be defaulted.
application_domain:
# replicas
replicas: 1
# port
port: 9000
# webhookSecret: will be randomly generated if not defined explicitly
#webhookSecret: mysecret
# secrets to mount as env vars
secrets:
  - name: ocd-builder-credentials
    prefix: false